### ISSUE TITLE
metrics-mongodb.rb doesn't work with mongo 4.2.3

### ISSUE THREAD

**Issue by jindraj** [sensu-plugins/sensu-plugins-mongodb#67]
It won't work probably with any 4.2.x minor version. The same check against 4.0.2 works.

```Check failed to run: undefined method `[]' for nil:NilClass, ["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-mongodb-2.1.0/lib/sensu-plugins-mongodb/metrics.rb:321:in `server_metrics'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-mongodb-2.1.0/bin/metrics-mongodb.rb:121:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-2.0.1/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]```

I traced the issue to [metrics.repl.preload](https://docs.mongodb.com/v4.0/reference/command/serverStatus/#serverstatus.metrics.repl.preload) and [metrics.storage.*](https://docs.mongodb.com/v4.0/reference/command/serverStatus/#serverstatus.metrics.storage.freelist.search.bucketExhausted)
